import Head from "next/head";
import Image from "next/image";
import { Roboto_Slab } from "next/font/google";
import styles from "@components/styles/Home.module.css";

const robotoSlab = Roboto_Slab({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Netflix Clone App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Netflix</h1>
      </div>
    </>
  );
}
