import Head from "next/head";
import Image from "next/image";
import { Roboto_Slab } from "next/font/google";
import styles from "@components/styles/Home.module.css";
import Banner from "@components/components/banner/banner";
import NavBar from "@components/components/nav/navbar";
import Card from "@components/components/card/card";

const robotoSlab = Roboto_Slab({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Netflix Clone App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavBar username="mariiamatv@gmail.com" />

        <Banner
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford.webp"
        />

        <Card imgUrl="/static/clifford.webp" size="large" />
        <Card imgUrl="/static/clifford.webp" size="medium" />
        <Card imgUrl="/static/clifford.webp" size="small" />
      </div>
    </>
  );
}
