import Head from "next/head";
import Image from "next/image";
import { Roboto_Slab } from "next/font/google";
import styles from "@components/styles/Home.module.css";
import Banner from "@components/components/banner/banner";
import NavBar from "@components/components/nav/navbar";
import SectionCards from "@components/components/card/section-cards";
import { getVideos, getPopularVideos } from "@components/lib/videos";

const robotoSlab = Roboto_Slab({ subsets: ["latin"] });

export async function getServerSideProps(context) {
  const disneyVideos = await getVideos("disney trailer");
  const productivityVideos = await getVideos("Productivity");
  const travelVideos = await getVideos("travel ukraine");
  const popularVideos = await getPopularVideos();

  // const popularVideos = await getVideos();

  return {
    props: {
      disneyVideos: JSON.parse(JSON.stringify(disneyVideos)),
      productivityVideos: JSON.parse(JSON.stringify(productivityVideos)),
      travelVideos: JSON.parse(JSON.stringify(travelVideos)),
      popularVideos: JSON.parse(JSON.stringify(popularVideos)),
    },
  };
}

export default function Home({
  disneyVideos,
  productivityVideos,
  travelVideos,
  popularVideos,
}) {
  console.log({ disneyVideos });
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Netflix Clone App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.main}>
          <NavBar username="mariiamatv@gmail.com" />

          <Banner
            title="Clifford the red dog"
            subTitle="a very cute dog"
            imgUrl="/static/clifford.webp"
          />

          <div className={styles.sectionWrapper}>
            <SectionCards title="Disney" videos={disneyVideos} size="large" />
            <SectionCards title="Travel" videos={travelVideos} size="small" />
            <SectionCards
              title="Productivity"
              videos={productivityVideos}
              size="medium"
            />
            <SectionCards title="Popular" videos={popularVideos} size="small" />
          </div>
        </div>
      </div>
    </>
  );
}
